package myexceptions;
import java.io.IOException;
import java.util.Scanner;

//write a program to accept two numbers and display their division

class MyException extends Exception
{
	  MyException()
	  {
		  System.out.println("My own exception created");
	  }
}

public class Dividewithcare1 {
	
public static void main(String[] args) throws IOException {
	//declare two variables to store two numbers
	int a,b,c=0;
	//accept data from keyboard
	//create input stream object
	Scanner sc=new Scanner(System.in);
	//accept data from command line
    try{
    /*
	* a=Integer.parseInt(args[0]); b=Integer.parseInt(args[1]);
	*/
System.out.println("Enter first number:");
a=sc.nextInt();

System.out.println("Enter second number");
b=sc.nextInt();
   
    c=a/b;
    }catch(ArithmeticException ae)
    {
	
    	System.out.println("We can not divide any number with ZERO!!!");
    }catch(NumberFormatException ne)
    {
    	System.out.println("Only number required,not an alphabet");
    }catch(Exception e)
    {
    	try
    	{
    	throw new MyException();
    	}catch(Exception ex){ System.out.println("can not handle");
    	}
    	finally
    	{
    	sc.close();
	    System.out.println("finally block executed");
    }
    System.out.println("Result="+c);
    }
}

